# Generated by Django 5.1.1 on 2024-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
