# Generated by Django 5.1.1 on 2024-09-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_products_price"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
