# Generated by Django 5.1.1 on 2024-09-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_category_product_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent_category",
        ),
    ]
